### ISSUE TITLE
libtermcap.so.2: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by thruesport** [Zemke/tippspiel2#56]
this is my error message:
tippspiel2-spring/target/pgsql-9.1.0-1/pgsql/bin/initdb: error while loading shared libraries: libtermcap.so.2: cannot open shared object file: No such file or directory

My os is an Ubuntu 16.04 LTS

**Comment by Zemke** [comment]
This is not related to Tippspiel2. This might be a local problem or you might find help from the creators of the Embedded PostgreSQL developers at [yandex-qatools/postgresql-embedded](https://github.com/yandex-qatools/postgresql-embedded).
