### ISSUE TITLE
Fixture dates are shown in English regardless of chosen localization

### ISSUE THREAD

**Issue by morckx** [Zemke/tippspiel2#63]
at least in in /bets and /fixtures/.../bets, e. g.:

Russland 
Saudi Arabien
Thursday, June 14, 17:00

**Comment by Zemke** [comment]
What’s your OS’s and your browser’s locale? I knew it wouldn’t localize according to the setting, but I thought the format was in either your OS’s or your browser’s locale.

**Comment by morckx** [comment]
My OS locale is `de_DE.utf8`

My browsers are also set to prefer German. My Opera's JavaScript browser information looks like this (but I also have the bug with Firefox and Chrome):
```
navigator.browserLanguage: undefined
navigator.language: de
navigator.userAgent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.18 Safari/537.36 OPR/55.0.2962.0 (Edition developer)
date: Wed Jun 13 2018 13:38:41 GMT+0200 (Mitteleuropäische Sommerzeit)
date.toLocaleDateString(): 13.6.2018
date.toLocaleTimeString(): 13:38:41
date.toLocaleString(): 13.6.2018, 13:38:41
date.toUTCString(): Wed, 13 Jun 2018 11:38:41 GMT
date.getTimezoneOffset(): -120
```
